fix lbt mods
pypeit/PypeIt pull request #1129
Opened 2021-01-19 18:38 UTC by feigewang

fix LBT MODS blue side.

2021-01-19 21:47 UTC, profxj requested changes
pass tests (unit + DevSuite on LBT only) and I'll approve.

Thanks!

2021-01-19 21:57 UTC, tepickering approved these changes
LGTM! i am not MODS-savvy so i can't speak to the specific changes to the parameters, but the code changes look straightforward and self-contained.

2021-01-19 22:00 UTC, tepickering commented
looks like there's a test failure against `astropy-master`, but it's not relevant to this work....

2021-01-19 22:02 UTC, jhennawi commented on pypeit/spectrographs/lbt_mods.py
> +            specflip        = True,
How was this ever working before if the wavelength axis was flipped. I don't see how you could have gotten a wavelength solution out of full_template with flipped wavelength direction.

2021-01-19 22:02 UTC, profxj commented
@tepickering -- is it possible to initiate the CI tests on the `develop` branch?
i.e. to see if that is now failing (I presume it).

2021-01-19 22:02 UTC, jhennawi commented on pypeit/spectrographs/lbt_mods.py
> +            specflip        = True,
Ah okay, now I see you checked in a new arxiv, so I guess you flipped it.

2021-01-19 22:03 UTC, jhennawi approved these changes
Approved. I presume this spectrograph is in the dev suite? Please run just that one test before you merge.

2021-01-19 22:07 UTC, tepickering commented
i haven't seen this test failure in my branch which is pretty closely synced to `develop`. digging a little deeper. working on setting up scheduled workflows that check `master` weekly and `develop` daily to help flag when upstream changes might bite us.

2021-01-19 22:13 UTC, profxj commented
Please do, @tepickering .  Thanks!

2021-01-19 22:14 UTC, profxj approved these changes
approving now

2021-01-20 01:52 UTC, tepickering commented
i can't reproduce that `astropydev` failure locally. also didn't show up in the last CI run against my fork yesterday which was up-to-date with `develop`. will revisit tomorrow when i set up my PR.

2021-01-20 02:10 UTC, feigewang commented
Both tests passed. Note that the failure on the test_scripts are caused by my Ginga problem. 

<img width="744" alt="Screen Shot 2021-01-19 at 7 08 29 PM" src="https://user-images.githubusercontent.com/23131361/105117504-d1189280-5a89-11eb-97ca-96d65dffd3b3.png">
<img width="1254" alt="Screen Shot 2021-01-19 at 6 44 03 PM" src="https://user-images.githubusercontent.com/23131361/105117515-d70e7380-5a89-11eb-9ecc-7e935be66880.png">

2021-01-20 18:35 UTC, merged