Make par_outfile a real command line parameter
pypeit/PypeIt pull request #1138
Opened 2021-02-08 22:26 UTC by eteq

Looks to me like this was just a copy-and-paste error since this really shouldn't ever be a boolean.

2021-02-10 10:12 UTC, jhennawi approved these changes
Good catch.

2021-02-10 10:13 UTC, jhennawi reviewed
Good catch, but you need to pull in the updated release into this branch, before we can marge.

2021-02-10 10:15 UTC, jhennawi requested changes
Pull in the updated release branch then it will be approved.

2021-02-23 00:00 UTC, kbwestfall approved these changes
Looks good!

2021-02-24 13:58 UTC, jhennawi approved these changes
Thanks!

2021-02-24 13:58 UTC, merged