Updates to quicklook
pypeit/PypeIt pull request #1177
Opened 2021-04-27 01:03 UTC by badpandabear

This is a companion PR to [](https://github.com/pypeit/PypeIt-development-suite/pull/148) in the dev suite. It changes `ql_keck_mosfire.py` to use wild card patterns to find QL masters. This way the information on which files to use is only hard coded in the `build_ql_masters` script.

If that PR is not approved this PR should also not be approved, because in that case neither script will have the files for MOSFIRE QL Masters

2021-04-27 02:34 UTC, jhennawi commented on pypeit/scripts/ql_keck_mosfire.py
> +def find_single_file(file_pattern):
Nice, should we move this to core.utils. It looks like other routines would benefit.

2021-04-27 02:34 UTC, jhennawi requested changes
Minor comment. Otherwise looks great.

2021-04-27 14:50 UTC, profxj approved these changes
approved

2021-04-27 23:33 UTC, badpandabear commented
Unit tests:

> ================ 271 passed, 423 warnings in 768.06s (0:12:48) =================

Dev Suite:

> --- PYPEIT DEVELOPMENT SUITE PASSED 108/108 TESTS (Masters ignored) ---
> Testing Started at 2021-04-26T23:13:58.556808
> Testing Completed at 2021-04-27T04:13:21.428376
> Total Time: 4:59:22.871568
>

2021-04-28 23:06 UTC, jhennawi approved these changes

2021-04-28 23:11 UTC, merged