Adding LTT7379 to the list of standards
pypeit/PypeIt pull request #1202
Opened 2021-06-14 16:55 UTC by ntejos

Adding LTT7379 to the list of standards, following instructions in https://pypeit.readthedocs.io/en/release/fluxing.html#adding-a-standard-star

2021-06-14 22:28 UTC, profxj requested changes
Somehow there are 30 files touched here.
am guessing this is branched off a branch
that is currently a PR.  

But we might need to re-issue this.

Do you agree @kbwestfall ?

2021-06-14 22:31 UTC, kbwestfall commented
Yeah, these should go away once  #1200 is merged.

2021-06-16 15:45 UTC, profxj approved these changes
Looks good.  Thx!

2021-06-16 17:17 UTC, badpandabear approved these changes

2021-06-16 17:24 UTC, merged