Deimos coadd2d debug
pypeit/PypeIt pull request #1235
Opened 2021-07-28 18:00 UTC by ShaneBechtel

This small PR fixes some bugs that were identified in Pypeit 2DCoadds for combinations of frames that are dithered in central wavelength.

2021-07-28 21:07 UTC, profxj approved these changes
minor comments from me.
thx for this!

note -- you have to manage the CHANGES conflict

2021-07-28 21:07 UTC, profxj commented on pypeit/specobjs.py
> +            slitorder:
Fill in descriptions for these `Args`,  thx!

2021-07-29 09:55 UTC, deborape approved these changes
Looks good! Only one minor comment.

2021-07-29 09:55 UTC, deborape commented on pypeit/specobjs.py
> +            indx = (np.abs(self.SLITID - slitorder) <= toler) & (self.OBJID == objid)
I guess you also want to decide if this `toler` is 5, 3, or a parameter. Maybe add a TODO?

2021-08-07 13:04 UTC, profxj commented
@ShaneBechtel -- merge when you are happy with this

2021-08-24 13:14 UTC, profxj requested changes
Items keep getting added to this PR.
Am going to close and have it be reopened when ready.

2021-08-24 13:14 UTC, profxj commented
Am closing until this PR is ready.  Items
keep getting added in and those have not
been reviewed...

2021-08-24 13:14 UTC, closed without merging