Astrometric corrections for KCWI
pypeit/PypeIt pull request #1253
Opened 2021-08-24 13:00 UTC by rcooke-ast

This update includes a few KCWI updates:
* allows the contbars frame to be used (or not) for the astrometric correction
* adds KCWI documentation

2021-08-24 20:42 UTC, profxj approved these changes
Solid.  Only one nit from me.

2021-08-24 20:42 UTC, profxj commented on pypeit/io.py
> +    if codetime < 60.0:
add a brief doc string

2021-08-24 20:42 UTC, profxj commented on pypeit/slittrace.py
> +        # Debugging when astrometric=True
remove?

2021-08-25 23:02 UTC, debora-pe approved these changes
Looks good to me! Only minor comments.
The most important one is about the `skyimage` package.

Please, also post the results of the tests.

2021-08-25 23:02 UTC, debora-pe commented on pypeit/slittrace.py
> +from skimage import transform as tf
`skyimage` is not a package that is included in the Pypeit requirements. That should be done.

2021-08-25 23:02 UTC, debora-pe commented on pypeit/slittrace.py
> +        initial : bool
This should be `astrometric`?

2021-08-25 23:02 UTC, debora-pe commented on doc/skysub.rst
> +the sky regions, press the "Continue (and don't save changes)".
button

2021-08-25 23:07 UTC, tepickering commented on pypeit/slittrace.py
> +from skimage import transform as tf
note that the `skimage` module is provided by the `scikit-image` package. and, yes, `scikit-image` needs to be added to the requirements in `setup.cfg`.

2021-08-26 09:50 UTC, rcooke-ast reviewed
Comments addressed - thanks all!

2021-08-26 09:50 UTC, rcooke-ast commented on doc/skysub.rst
> +the sky regions, press the "Continue (and don't save changes)".
Done!

2021-08-26 09:50 UTC, rcooke-ast commented on pypeit/io.py
> +    if codetime < 60.0:
Thanks - I should have caught that...

2021-08-26 09:50 UTC, rcooke-ast commented on pypeit/slittrace.py
> +        initial : bool
Quite right - good catch!!

2021-08-26 09:50 UTC, rcooke-ast commented on pypeit/slittrace.py
> +        # Debugging when astrometric=True
done (and I've also deleted the debugging comments below, too...)

2021-08-26 09:50 UTC, rcooke-ast commented on pypeit/slittrace.py
> +from skimage import transform as tf
Given that `scikit-image` is only used when creating datacubes (and only when an astrometric correction is requested) then I'm tempted to not add this to the list of "must haves" for PypeIt. I've come up with an alternative solution (to catch an import error, and added some info to the installation and KCWI docs) let me know what you think!

2021-08-26 10:46 UTC, jhennawi commented on pypeit/core/datacube.py
> +        flexure = None  #spec2DObj.sci_spat_flexure
Can you get rid of this line and set flexure to be None in the keyword argument online 625?

2021-08-26 10:47 UTC, jhennawi commented on pypeit/io.py
> +
Does this rather belong in pypeit.uitls?

2021-08-26 10:47 UTC, jhennawi commented on pypeit/pypeit.py
> +        msgs.info(io.get_time_string(time.time()-self.tstart))
Thanks for cleaning this up.

2021-08-26 10:49 UTC, jhennawi commented on pypeit/slittrace.py
> +                        astrometric=True, initial=True, flexure=None):
Can you please add a comment to the doc that this method is currently only used for IFUs?

2021-08-26 10:50 UTC, jhennawi requested changes
Very minor comments. Thanks for this PR.

2021-08-26 10:50 UTC, jhennawi approved these changes

2021-08-26 11:20 UTC, rcooke-ast reviewed
@jhennawi comments addressed - thanks!

2021-08-26 11:20 UTC, rcooke-ast commented on pypeit/core/datacube.py
> +        flexure = None  #spec2DObj.sci_spat_flexure
There are multiple instances of flexure in this code, so I think having a single place to change this makes more sense... just in case flexure is supported with future IFUs.

2021-08-26 11:20 UTC, rcooke-ast commented on pypeit/io.py
> +
Sure - I'll put it there!

2021-08-26 11:20 UTC, rcooke-ast commented on pypeit/pypeit.py
> +        msgs.info(io.get_time_string(time.time()-self.tstart))
np

2021-08-26 11:20 UTC, rcooke-ast commented on pypeit/slittrace.py
> +                        astrometric=True, initial=True, flexure=None):
Done!

2021-08-26 11:24 UTC, rcooke-ast commented
Tests pass... merging
![image](https://user-images.githubusercontent.com/12585758/130954556-68b376e8-cb47-49b6-a727-a973cd31179a.png)

2021-08-26 11:25 UTC, merged