Check header for consistent instrument name
pypeit/PypeIt pull request #1279
Opened 2021-10-26 19:17 UTC by profxj

For the chosen spectrograph, check that the instrument
name in the header matches expectations.  If possible.

Throw a warning if not.

Address #1276

2021-10-26 19:18 UTC, profxj commented
I was having it throw an error instead of a warning,
but already found some edge cases and don't wish
the code to crash on this check.

2021-10-26 19:32 UTC, kbwestfall reviewed
Looks great!  Just a couple of minor comments.  We should add the header names for as many of the "supported" spectrographs as we can in this PR.

2021-10-26 19:32 UTC, kbwestfall commented on pypeit/spectrographs/spectrograph.py
> +      Usually the INSTRUME card.
Formatting like this is going to be ignored when sphinx makes the docs.  I.e., the first and second line are just separated by a space and formatted in html.  You should treat docstrings like this as unformatted text.

2021-10-26 19:32 UTC, kbwestfall commented on pypeit/spectrographs/spectrograph.py
> +                msgs.warn(f"You may have chosen the wrong PypeIt spectrograph name")
Here and above, I think it would be better if you didn't call `warn` twice.  Just use a long string:
```
msgs.warn("The instrument read from the headers of your data do not match the selected "
          f"spectrograph.  Found '{instr_names[0]}', expected '{self.header_name}'.  "
          "Either you're using the wrong data or the wrong spectrograph name.")
```
Note you can mix and match string types; "f-strings" can be combined with normal strings.

2021-10-26 19:32 UTC, kbwestfall commented on pypeit/spectrographs/keck_lris.py
> +import astropy
remove?

2021-10-26 20:51 UTC, jhennawi requested changes
Looks good. Is there a reason why only a handful of instruments have the header_name defined?

2021-10-26 20:56 UTC, profxj commented
Will add some more but it is laborious to manually find these..

2021-10-27 21:40 UTC, profxj commented on pypeit/spectrographs/spectrograph.py
> +      Usually the INSTRUME card.
roger

2021-10-27 21:41 UTC, profxj commented on pypeit/spectrographs/spectrograph.py
> +                msgs.warn(f"You may have chosen the wrong PypeIt spectrograph name")
done!

2021-10-27 21:41 UTC, profxj commented on pypeit/spectrographs/keck_lris.py
> +import astropy
removed

2021-10-27 21:49 UTC, profxj commented
`test_setups.py`

================== 21 passed, 22 warnings in 90.38s (0:01:30) ==================

2021-10-27 22:04 UTC, kbwestfall reviewed
There are still lots of spectrographs missing.  Can we provide header_name for all the setups in the dev-suite?

2021-10-27 22:04 UTC, kbwestfall commented on pypeit/spectrographs/keck_kcwi.py
> +    header_name = 'KCWI'
Do we need this line somewhere in keck_kcwi.py? 
```
self.meta['instrument'] = dict(ext=0, card='INSTRUME')
```

2021-10-27 22:04 UTC, kbwestfall commented on pypeit/spectrographs/spectrograph.py
> +    Usually the INSTRUME card.
Stick a period after "Header" on the first line.

2021-10-28 13:49 UTC, profxj commented
=============== 302 passed, 5091 warnings in 1421.52s (0:23:41) ================

2021-10-28 13:50 UTC, profxj commented on pypeit/spectrographs/keck_kcwi.py
> +    header_name = 'KCWI'
good catch

2021-10-28 13:50 UTC, profxj commented on pypeit/spectrographs/spectrograph.py
> +    Usually the INSTRUME card.
added

2021-10-29 18:36 UTC, profxj commented
================== 21 passed, 22 warnings in 86.50s (0:01:26) ==================

2021-10-29 19:07 UTC, kbwestfall approved these changes
Thanks for filling in more spectrographs!

2021-11-15 23:42 UTC, jhennawi approved these changes
Make sure you merge in develop before you merge since you cannot merge now.

2021-11-16 00:05 UTC, merged