Move KOA archiving code from pypeit_collate_1d to the ADAP repo
pypeit/PypeIt pull request #1315
Opened 2022-01-13 01:18 UTC by badpandabear

This PR is to remove all of the ADAP specific archiving code from pypeit_collate_1d so it can be moved to the ADAP repo. This involved removing the archive_root and pypeit_file arguments from pypeit_collate_1d, the specific code involved in building the metadata for archiving, and the related unit tests.

Unit test results:
======= 306 passed, 545 warnings in 915.71s (0:15:15) =======

Dev suite results are in progress (although I'm not sure they're needed as nothing in this PR affects the dev suite)

2022-01-13 01:34 UTC, badpandabear commented
https://github.com/pypeit/adap/pull/1 is the corresponding PR in the adap repo

2022-01-18 20:55 UTC, profxj approved these changes
This all looks kosher to me.

thx

2022-01-18 20:55 UTC, profxj commented
And I agree, no need to run the DevSuite.

2022-01-19 04:23 UTC, deborape requested changes
Hi @badpandabear ! Looks very good. I have very minor comments. Also, I notice that the file `collate1d.par` is a bit confusing as it is now because it includes all the existing parsets and the parset for the main reduction do not even match the used parsets. Could you just include in `collate1d.par` the parsets for [collated1d] and [coadd1d], which are the only ones used by collated1d? It would also be good to copy `collate1d.par` to the KOA archive directory (this is for the adap repo).

2022-01-19 04:23 UTC, debora-pe commented on doc/collate1d.rst
>  | med_s2n         | The signal to noise ratio of the extracted object.        |
This should be s2n

2022-01-19 04:23 UTC, debora-pe commented on doc/collate1d.rst
>  | med_s2n         | The signal to noise ratio of the extracted object.        |
Also in `collate_report.dat`

2022-01-19 04:23 UTC, debora-pe commented on pypeit/scripts/collate_1d.py
>          - ``collate_report.dat`` contains metadata to report on the coadded output files
I have noticed that `collate_report.dat` has a few less columns than `coadded_files_meta.dat`. I think it would be useful if `collate_report.dat` is identical to `coadded_files_meta.dat`.

2022-01-19 04:23 UTC, deborape commented on doc/collate1d.rst
>      # Where to look for .pypeit files when building an archive.
The parset `pypeit_file` also does not exist anymore here

2022-01-25 03:56 UTC, deborape approved these changes
Thanks for the changes @badpandabear! I added 2 very small comments. I really don't need to check them again, so I'm approving now and when you are ready you can merge.
Thanks!

2022-01-25 03:56 UTC, deborape commented on doc/collate1d.rst
>  | med_s2n         | The signal to noise ratio of the extracted object.        |
[I though I wrote this comment before, but I cannot find it] Do you mind rounding `s2n` and `wave_rms` to the 2nd and 3rd decimal digits, respectively (how is done in spec1d*.txt)? It helps the readability. Thanks!

2022-01-25 03:56 UTC, deborape commented on pypeit/scripts/collate_1d.py
> +        config_lines = par['collate1d'].to_config(section_name='collate1d') + ['']
Do you mind adding to the `.to_config()` function the parameter `include_descr=False`? I found it helps the readability not having all those descriptions. Thanks!

2022-01-26 02:01 UTC, merged