KCWI Frame-typing
pypeit/PypeIt pull request #1363
Opened 2022-02-28 22:14 UTC by kbwestfall

This PR provides some better default frame typing for KCWI.  This is development based on some work I did reducing some of my own KCWI data.  I'm not likely to make much more progress beyond this anytime soon, so I wanted to get this in now.

Tests pass.
```=== 324 passed in 1287.85s (0:21:27) ===```

Dev-suite launched.

2022-02-28 22:14 UTC, kbwestfall commented
PS - This also updates `develop` for the recent 1.8.1 tag.

2022-02-28 22:26 UTC, jhennawi commented on pypeit/display/display.py
>      """
can you please document allow_new

2022-02-28 22:27 UTC, jhennawi commented on pypeit/par/util.py
>      Args:
sorted --> sort in the docs.

2022-02-28 22:28 UTC, jhennawi requested changes
Looks good @kbwestfall. Minor documentation request and then you need to run the tests and dev suite, but otherwise consider it approved.

2022-02-28 23:01 UTC, kbwestfall commented on pypeit/display/display.py
>      """
Done.

2022-02-28 23:01 UTC, kbwestfall commented on pypeit/par/util.py
>      Args:
Good catch!  Done.

2022-03-01 11:35 UTC, rcooke-ast approved these changes
Seems all good to me!

The one thing I'm cautious about is that there was a period (up until Dec 2019) when the frame typing was made more complicated by arcs being turned on with the shutter closed (e.g. a flat was being taken and the arc was leaking into the flat). I don't think the changes capture this problem with "historic" datasets, so it might be worthwhile adding a comment to be aware of this for folks reducing their old KCWI data.

Thanks for the PR!!

2022-03-01 15:25 UTC, kbwestfall commented
1 dev-suite failure.  Investigating:
```
--- PYPEIT DEVELOPMENT SUITE FAILED 1/135 TESTS (Masters ignored) ---
Failed tests:
    gemini_gnirs/32_SB_SXD pypeit_coadd_1dspec
Skipped tests:
    gemini_gnirs/32_SB_SXD pypeit_coadd_2dspec
    gemini_gnirs/32_SB_SXD pypeit_tellfit
Testing Started at 2022-02-28T22:18:35.096075
Testing Completed at 2022-03-01T07:33:32.558804
Total Time: 9:14:57.462729
```

2022-03-01 15:32 UTC, kbwestfall commented
> The one thing I'm cautious about is that there was a period (up until Dec 2019) when the frame typing was made more complicated by arcs being turned on with the shutter closed (e.g. a flat was being taken and the arc was leaking into the flat). I don't think the changes capture this problem with "historic" datasets, so it might be worthwhile adding a comment to be aware of this for folks reducing their old KCWI data.

My data was from 2018, so I saw the issue with, e.g., the internal cals being on during the dome flat exposures, even if their shutters were closed.  The code is currently strict concerning these cases, requiring the user to type files like these themselves.  I tested the file typing against the data in the dev-suite, and the new code works fine.  I'm happy to test more data if you point me to it.

2022-03-01 15:46 UTC, rcooke-ast commented
Great! That sounds good to me then!!

2022-03-01 18:31 UTC, kbwestfall commented
The fix required a change to the object name.  See https://github.com/pypeit/PypeIt-development-suite/pull/190.  Afterburn scripts for gnirs now pass:
```
% ./pypeit_test afterburn -i gemini_gnirs -s 32_SB_SXD
Running tests on the following instruments:
    gemini_gnirs

Reducing data from gemini_gnirs for the following setups:
    32_SB_SXD

 0 passed/ 0 failed/ 0 skipped STARTED gemini_gnirs/32_SB_SXD pypeit_sensfunc
 1 passed/ 0 failed/ 0 skipped PASSED  gemini_gnirs/32_SB_SXD pypeit_sensfunc
 1 passed/ 0 failed/ 0 skipped STARTED gemini_gnirs/32_SB_SXD pypeit_flux_setup
 2 passed/ 0 failed/ 0 skipped PASSED  gemini_gnirs/32_SB_SXD pypeit_flux_setup
 2 passed/ 0 failed/ 0 skipped STARTED gemini_gnirs/32_SB_SXD pypeit_flux
 3 passed/ 0 failed/ 0 skipped PASSED  gemini_gnirs/32_SB_SXD pypeit_flux
 3 passed/ 0 failed/ 0 skipped STARTED gemini_gnirs/32_SB_SXD pypeit_coadd_1dspec
 4 passed/ 0 failed/ 0 skipped PASSED  gemini_gnirs/32_SB_SXD pypeit_coadd_1dspec
 4 passed/ 0 failed/ 0 skipped STARTED gemini_gnirs/32_SB_SXD pypeit_coadd_2dspec
 5 passed/ 0 failed/ 0 skipped PASSED  gemini_gnirs/32_SB_SXD pypeit_coadd_2dspec
 5 passed/ 0 failed/ 0 skipped STARTED gemini_gnirs/32_SB_SXD pypeit_tellfit
 6 passed/ 0 failed/ 0 skipped PASSED  gemini_gnirs/32_SB_SXD pypeit_tellfit

--- PYPEIT DEVELOPMENT SUITE PASSED 6/6 TESTS (Masters ignored) ---
Testing Started at 2022-03-01T10:07:12.560313
Testing Completed at 2022-03-01T10:16:53.520771
Total Time: 0:09:40.960458
```

2022-03-01 23:33 UTC, jhennawi approved these changes
Thanks!

2022-03-02 21:06 UTC, merged