DEIMOS mosaic
pypeit/PypeIt pull request #1378
Opened 2022-04-14 22:56 UTC by deborape

Constructed mosaic for DEIMOS. Four mosaics total (one per each blue-red detectors pair). The blue detectors are the only ones to be transformed.

Documentation added.

Related Dev Suite PR: https://github.com/pypeit/PypeIt-development-suite/pull/194 (please consider reviewing that too)

Unrelated changes:
- several fixes to manual extraction
- fix bug with  `reduce_bpm`, which was updated in `objFind`, but not propagated to `Extract`
- fix bug in `chk_noise_2dspec`
- address issue #1359

2022-04-15 15:08 UTC, profxj requested changes
Great stuff!

Only a few minor requests from me.

2022-04-15 15:08 UTC, profxj commented on doc/deimos.rst
> +Also, note that this script works only id the a mosaic reduction is not
typo?  I think it should read  "only i[f] the [] mosaic reduction"..

2022-04-15 15:08 UTC, profxj commented on pypeit/manual_extract.py
> +            # det_strip will be a list of a single number (no mosaic) or 2 numbers (mosaic)
nice.  thanks for adding this!

2022-04-15 15:08 UTC, profxj commented on pypeit/par/pypeitpar.py
> +        defaults['return_negative'] = False
do we have a test of this in the DevSuite?  

If not, can we?

2022-04-15 15:08 UTC, profxj commented on pypeit/par/pypeitpar.py
> +                          'KEck/DEIMOS it would be ``[(1, 5), (2, 6), (3, 7), (4, 8)]`` ' \
Do we have a test of this in the DevSuite?  

If not, can we?

2022-04-15 15:08 UTC, profxj commented on pypeit/scripts/chk_noise_2dspec.py
> +def get_flux_slit(spec2DObj, slitidx, pad=0):
please add a short doc string

2022-04-15 15:08 UTC, profxj commented on pypeit/spectrographs/gemini_gmos.py
> +        msc_order = 0
maybe put this in the `def` 

Is an easier spot to find (and then you can comment it there)

2022-04-15 15:08 UTC, profxj commented on pypeit/spectrographs/keck_deimos.py
> +        par['calibrations']['wavelengths']['n_final'] = 6
Is it possible to know here whether we are in mosaic mode and act accordingly?

same for `sigdetect` below..

2022-04-15 15:08 UTC, profxj commented on pypeit/spectrographs/keck_deimos.py
> +        if det is None:
I think this might have been used when trying to generate an image of all 8 detectors.  But can't quire recall.

2022-04-15 15:08 UTC, profxj commented on pypeit/spectrographs/keck_deimos.py
> +        # Hard coded for now. Order of the interpolation used to construct the mosaic
As with GMOS, I suggest we add this to the `def` call.

And presumably need to update the method in `spectorgraph.py`

2022-04-15 15:08 UTC, profxj commented on pypeit/spectrographs/keck_deimos.py
>              the array is 2D, there are detectors separated along the dispersion
Add a brief doc on what `mosaic` does

2022-04-18 18:16 UTC, kbwestfall approved these changes
Great, @deborape !  I fixed some of the minor typos directly, and then I had a couple of minor suggestions.  I'm approving now though.

2022-04-18 18:16 UTC, kbwestfall commented on pypeit/spectrographs/keck_deimos.py
> +    # geometry = {
I assume these are the parameters when you're interpolating the red chip only?  I would add a comment here about this and indicate that it's useful to keep these around for now.

2022-04-18 18:16 UTC, kbwestfall commented on pypeit/spectrographs/keck_deimos.py
> +        par['calibrations']['slitedges']['follow_span'] = 1000
Does it need to be this large?  I think it only needs to be large enough that the trace "following" algorithm can span the chip gap.  I ask because this might lead to some spurious traces being connected, but I'm not sure.

2022-04-18 18:16 UTC, kbwestfall commented on pypeit/spectrographs/keck_deimos.py
> +        par['calibrations']['slitedges']['follow_span'] = 1000
Does it need to be this large?  I think it only needs to be large enough that the trace "following" algorithm can span the chip gap.  I ask because this might lead to some spurious traces being connected, but I'm not sure.

2022-04-18 18:16 UTC, kbwestfall commented on pypeit/spectrographs/keck_deimos.py
> +        par['calibrations']['wavelengths']['n_final'] = 6
Good question.  It might be as simple as checking if there is a tuple in the detnum.

2022-04-18 18:16 UTC, kbwestfall commented on pypeit/spectrographs/keck_deimos.py
> +        if det is None:
The default `detnum` in `PypeItPar` is None, but I agree that this may never be the case now for DEIMOS.

2022-04-18 18:16 UTC, kbwestfall commented on pypeit/spectrographs/keck_deimos.py
> +        # DP: Still do not know if this is necessary
Same thing here.

2022-04-18 18:16 UTC, kbwestfall commented on pypeit/spectrographs/keck_deimos.py
> +        # DP: Still do not know if this is necessary
Same thing here.

2022-04-18 18:16 UTC, kbwestfall commented on pypeit/spectrographs/keck_deimos.py
> +        _ccdnum = [d for d in _det]
Does this mean `_ccdnum` and `_det` are identical?  Could you just set `_ccdnum` directly: `nimg, _ccdnum = self.validate_det(ccdnum)`?

2022-04-18 18:16 UTC, kbwestfall commented on pypeit/spectrographs/keck_deimos.py
> +        _ccdnum = [d for d in _det]
Does this mean `_ccdnum` and `_det` are identical?  Could you just set `_ccdnum` directly: `nimg, _ccdnum = self.validate_det(ccdnum)`?

2022-04-18 18:16 UTC, kbwestfall commented on pypeit/spectrographs/keck_deimos.py
> +            return np.array(['MSC{:02d}'.format(i+1) for i in range(len(self.allowed_mosaics))])
I would use the `pypeit.images.mosaic.Mosaic.get_name` method to set the mosaic name.

2022-04-18 18:16 UTC, kbwestfall commented on pypeit/spectrographs/keck_deimos.py
> +            return np.array(['MSC{:02d}'.format(i+1) for i in range(len(self.allowed_mosaics))])
I would use the `pypeit.images.mosaic.Mosaic.get_name` method to set the mosaic name.

2022-04-18 18:18 UTC, kbwestfall commented
Apologies.  For some reason, github made repeats of a bunch of my comments.  Let me know if you find anything confusing!

2022-04-19 01:45 UTC, debora-pe commented on pypeit/par/pypeitpar.py
> +                          'KEck/DEIMOS it would be ``[(1, 5), (2, 6), (3, 7), (4, 8)]`` ' \
Yes, we do. All the DEIMOS reductions include `detnum` in the pypeit file

2022-04-19 01:45 UTC, debora-pe commented on pypeit/scripts/chk_noise_2dspec.py
> +def get_flux_slit(spec2DObj, slitidx, pad=0):
Done

2022-04-19 01:45 UTC, debora-pe commented on pypeit/spectrographs/keck_deimos.py
> +    # geometry = {
Done

2022-04-19 01:45 UTC, debora-pe commented on pypeit/spectrographs/keck_deimos.py
> +        par['calibrations']['slitedges']['follow_span'] = 1000
The gap between the blue and red traces often was much larger than the chip gap. I tried different value, but this high value was giving the insurance to connect the traces.

2022-04-19 01:45 UTC, debora-pe commented on pypeit/spectrographs/keck_deimos.py
> +        par['calibrations']['wavelengths']['n_final'] = 6
Mosaic is the default. Only a different detnum added by the user in the pypeit file would make the reduction non-mosaic.
`config_specific_par` is run before making the merge with the parameters added by the user in pypeit file.  So at this point in the code, I cannot know whether is a mosaic or not.

2022-04-19 01:45 UTC, debora-pe commented on pypeit/spectrographs/keck_deimos.py
> +        if det is None:
Ok, I'll leave it, just in case.

2022-04-19 01:45 UTC, debora-pe commented on pypeit/spectrographs/gemini_gmos.py
> +        msc_order = 0
Done

2022-04-19 01:45 UTC, debora-pe commented on pypeit/spectrographs/keck_deimos.py
> +        # Hard coded for now. Order of the interpolation used to construct the mosaic
Done

2022-04-19 01:45 UTC, debora-pe commented on pypeit/spectrographs/keck_deimos.py
>              the array is 2D, there are detectors separated along the dispersion
Done

2022-04-19 01:45 UTC, debora-pe commented on pypeit/spectrographs/keck_deimos.py
> +            return np.array(['MSC{:02d}'.format(i+1) for i in range(len(self.allowed_mosaics))])
I used `spectrograph.get_det_name`

2022-04-19 01:45 UTC, debora-pe commented on pypeit/spectrographs/keck_deimos.py
> +        _ccdnum = [d for d in _det]
Yes, that's right! Changed, thanks.

2022-04-19 01:45 UTC, debora-pe commented on pypeit/par/pypeitpar.py
> +        defaults['return_negative'] = False
Added

2022-04-20 21:55 UTC, deborape commented
Dev Suite passes (There was a problem with one dataset, but resolved in the Dev Suite)
```
--- PYPEIT DEVELOPMENT SUITE FAILED 1/139 TESTS (Masters ignored) ---
Failed tests:
    keck_deimos/830G_M_9000_dither pypeit_coadd_2dspec
Skipped tests:
Testing Started at 2022-04-18T17:44:02.538756
Testing Completed at 2022-04-18T23:13:19.346728
Total Time: 5:29:16.807972
```


```
Running tests on the following instruments:
    keck_deimos

Reducing data from keck_deimos for the following setups:
    830G_M_9000_dither

 0 passed/ 0 failed/ 0 skipped STARTED keck_deimos/830G_M_9000_dither pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  keck_deimos/830G_M_9000_dither pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped STARTED keck_deimos/830G_M_9000_dither pypeit_coadd_2dspec
 2 passed/ 0 failed/ 0 skipped PASSED  keck_deimos/830G_M_9000_dither pypeit_coadd_2dspec

--- PYPEIT DEVELOPMENT SUITE PASSED 2/2 TESTS (Masters ignored) ---
Testing Started at 2022-04-19T14:16:07.631757
Testing Completed at 2022-04-19T15:54:44.587929
Total Time: 1:38:36.956172
```

2022-04-21 01:25 UTC, profxj approved these changes
Great stuff!

Approved.

2022-04-21 01:25 UTC, profxj commented
Merge when you wish.

2022-04-24 04:22 UTC, merged