Updates to tng_dolores.py
pypeit/PypeIt pull request #1389
Opened 2022-04-29 11:28 UTC by isabelmontoyaa

Updates on the header keywords for the tng/dolores spectrograph.
Changes on the 'saturation' and 'nonlinear' parameters of the detector.
Added the config_specific_par() function to set the wavelength
calibration lamps and arx_file.

Added the wavlength calibration file for tng/dolores LR-B grism made
with pypeit_identify.

2022-04-29 11:49 UTC, rcooke-ast approved these changes
Looks good to me!

2022-04-29 14:26 UTC, rcooke-ast commented on pypeit/spectrographs/tng_dolores.py
>              gain            = np.atleast_1d(0.97),
I can't comment on the lines below, but you will need to replace the following lines:

datasec         = np.atleast_1d('[1:2045,51:]'),
oscansec        = np.atleast_1d('[2054:,51:]'),

2022-04-29 17:42 UTC, profxj requested changes
This is great.  I'll approve once we have a test
in the DevSuite up and running.

2022-04-29 17:42 UTC, profxj commented on pypeit/spectrographs/tng_dolores.py
> +            par['calibrations']['wavelengths']['method'] = 'full_template'#'holy-grail'
please remove the holy-grail comment

2022-04-29 19:43 UTC, rcooke-ast commented on pypeit/spectrographs/tng_dolores.py
>              ysize           = 1.,
Also, please remove the commented out code on lines 27,28,29 - thanks!

2022-04-29 20:07 UTC, rcooke-ast commented
Added a dev suite test... which passes
<img width="436" alt="image" src="https://user-images.githubusercontent.com/12585758/166062170-35adbd4a-2a37-4237-a67a-86bcbfcbcfde.png">

2022-04-30 18:57 UTC, profxj commented
DevSuite companion:   https://github.com/pypeit/PypeIt-development-suite/pull/199

2022-05-02 13:14 UTC, profxj approved these changes
all good

2022-05-02 13:41 UTC, merged