Hotfix for parset
pypeit/PypeIt pull request #1610
Opened 2023-06-19 18:04 UTC by rcooke-ast

This hotfix fixes the single element list error in the parset. For further details, see Issue #842...

2023-06-20 10:35 UTC, profxj requested changes
Looks good, but can we add a new unit test to check it?

2023-06-20 14:47 UTC, jhennawi approved these changes

2023-06-20 16:36 UTC, rcooke-ast commented
> Looks good, but can we add a new unit test to check it?

Good idea... several checks added!

2023-06-21 21:09 UTC, profxj approved these changes
thx!

2023-06-22 10:24 UTC, merged