LRIS red mark4 mask ingestion
pypeit/PypeIt pull request #1624
Opened 2023-07-06 12:03 UTC by SunilSimha

As titled. I've tweaked the code and now it correctly ingests mask design information for the red side mark4 detector.

2023-07-06 12:51 UTC, profxj requested changes
Thanks for this.

Please make sure to add a test in the DevSuite
which includes a `vet` test that insures things 
are behaving as desired.

I can help

2023-07-06 12:51 UTC, profxj commented on pypeit/spectrographs/keck_lris.py
> +            alpha = sep.to('arcsec') * np.cos(PA-self.slitmask.posx_pa*units.deg-180*units.deg)
is this `-180deg` rotation true for *all* LRIS detectors, or only `mark4`?

2023-07-06 13:31 UTC, SunilSimha commented on pypeit/spectrographs/keck_lris.py
> +            alpha = sep.to('arcsec') * np.cos(PA-self.slitmask.posx_pa*units.deg-180*units.deg)
Oops. That's not supposed to be there at all. :)
Removed.

2023-07-06 13:32 UTC, SunilSimha commented
Happy to include the test in the dev suite. Although, I'll need edit permissions to add files in that folder.

2023-07-06 15:05 UTC, profxj commented on pypeit/spectrographs/keck_lris.py
> +            alpha = sep.to('arcsec') * np.cos(PA-self.slitmask.posx_pa*units.deg-180*units.deg)
but how was it working with it?

2023-07-17 22:10 UTC, debora-pe requested changes
Hey @SunilSimha I'm OK with these changes here. As we discussed we should add some tests. Let me know if you need any help.

2023-07-19 15:15 UTC, profxj approved these changes
Approving

2023-07-19 19:57 UTC, debora-pe approved these changes
Approving

2023-07-20 13:36 UTC, merged