Air2vac correction for XShooter standards
pypeit/PypeIt pull request #1633
Opened 2023-07-16 19:14 UTC by freddavies

Finally addressing https://github.com/pypeit/PypeIt/issues/941, as the issue has become even more obvious for the UVB arm of XShooter. 

Might be worth checking whether any of the other standard files also need this fix...

2023-07-20 14:58 UTC, jhennawi requested changes
Hi @freddavies can you please modify the README file at: 

~/PypeIt/pypeit/data/standards/xshooter

To explicitly note that the data stored in the files is in air. Also, does the reference say anything about it?

2023-07-20 16:21 UTC, profxj approved these changes
nice catch

2023-07-20 19:19 UTC, freddavies commented
README updated.

> Also, does the reference say anything about it?

Unfortunately it does not say anything explicitly, but one can guess it from the fact that they are using the ESO pipeline to reduce the data, which spits out air wavelengths by default. Otherwise the only other evidence is the much better agreement between the model and the data in the absorption line cores...

2023-07-28 11:05 UTC, jhennawi approved these changes

2023-07-28 12:00 UTC, merged