KCWI scattered light
pypeit/PypeIt pull request #1661
Opened 2023-09-03 17:45 UTC by rcooke-ast

This PR includes the functionality to generate a (spectrograph dependent) scattered light model, and subtract this light from the input image. The scattered light should be removed before correcting for spatial and spectral illumination, so it has to be included in the rawimage class. Here is an example for the KCWI correction. This is based on the left, right, and central parts of the detector (i.e. the not illuminated parts of the detector). This is a pixelflat.

<img width="1453" alt="image" src="https://github.com/pypeit/PypeIt/assets/12585758/c98be68f-78b7-461e-bc94-96418dc487b7">

2023-09-07 18:13 UTC, kbwestfall requested changes
A few minor comments from me, and two questions:

 - Can you add a description of this approach to the `keck_kcwi.rst` doc?
 - Can we save the scattered light image somewhere?  In either or both of the `Flat` calilbration frame and the `spec2d` files?

2023-09-07 18:13 UTC, kbwestfall commented on pypeit/core/parse.py
> +                -- this must be of the form of tuple, for example: np.array([2,1])
Please check this formats as you expect when the docs are built.

2023-09-07 18:13 UTC, kbwestfall commented on pypeit/core/skysub.py
> +        conv_allkern[:, :, kk] = utils.rebinND(utils.convolve_fft(_input_img, kern, _input_msk), input_img.shape)
Nice catch!

2023-09-07 18:13 UTC, kbwestfall commented on pypeit/find_objects.py
> +
Nice catch!

2023-09-07 18:13 UTC, kbwestfall commented on pypeit/images/rawimage.py
> +            self.image[ii, :, :] -= scatt_img
For statements like this, I instead would do `self.image[ii] -= scatt_img`.  Is there a reason to include the colons (e.g., is there a subtle memory allocation issue)?

Another aside: If you don't know or don't want to specify the dimensionality of the remaining array dimensions, you can use and ellipsis: `self.image[ii,...] -= scat_img`.

2023-09-07 18:13 UTC, kbwestfall commented on pypeit/images/rawimage.py
> +        :func:`~pypeit.spectrograph.procimg.subtract_pattern`.
Fix this reference.

2023-09-07 18:13 UTC, kbwestfall commented on pypeit/spectrographs/keck_kcwi.py
> +        binning : (str, `numpy.ndarray`_, tuple):
Remove the parentheses.  I.e.,
```
binning : str, `numpy.ndarray`_, tuple
```

2023-09-07 18:13 UTC, kbwestfall commented on pypeit/spectrographs/keck_kcwi.py
> +            formats, refer to `~pypeit.core.parse.parse_binning`.
Include the `:func:` syntax:
```
:func:`~pypeit.core.parse.parse_binning`
```

2023-09-07 18:13 UTC, kbwestfall commented on pypeit/spectrographs/keck_kcwi.py
> +        scattlightr = np.nanmedian(frame[:, -40//spatbin:], axis=1)[:, None]
Can we avoid hard-coding these numbers?  I.e., can we get them from the detector object?

2023-09-07 18:13 UTC, kbwestfall commented on pypeit/spectrographs/spectrograph.py
> +            formats, refer to `~pypeit.core.parse.parse_binning`.
Same fixes for the type and the `:func:` syntax.

2023-09-07 18:13 UTC, kbwestfall commented on pypeit/spectrographs/keck_kcwi.py
> +        return scatt_img
Please add some inline comments that explain the steps being taken.

2023-09-07 18:13 UTC, kbwestfall commented on pypeit/core/datacube.py
> +                # skyImg = spec2DObj_sky.skymodel * exptime / skysub_exptime  # Sky counts
Can't really comment on the changes to this file, but are they worth commenting on in the CHANGES or keck_kcwi docs?

2023-09-23 11:09 UTC, jhennawi commented on pypeit/find_objects.py
> +        if self.par['reduce']['findobj']['skip_skysub']:
This should be upstream in the control flow where it is called. It is odd to call a skysub routine and then return zero behind the scenes. Better would be to just put this skip upstream so the user can see that sky subtraction is being skipped in the main control flow.

2023-09-23 11:10 UTC, jhennawi requested changes
Very minor comments. Thanks!

2023-09-27 13:59 UTC, rcooke-ast reviewed
Thanks @jhennawi and @kbwestfall - I've addressed your comments.

In the process, I have also merged in in PR #1678 to take advantage of the new way to document changes.

2023-09-27 13:59 UTC, rcooke-ast commented on pypeit/core/datacube.py
> +                # skyImg = spec2DObj_sky.skymodel * exptime / skysub_exptime  # Sky counts
Good point - I have added a note in the release docs

2023-09-27 13:59 UTC, rcooke-ast commented on pypeit/images/rawimage.py
> +        :func:`~pypeit.spectrograph.procimg.subtract_pattern`.
Fixed (I think!)

2023-09-27 13:59 UTC, rcooke-ast commented on pypeit/images/rawimage.py
> +            self.image[ii, :, :] -= scatt_img
I didn't know about ellipses - I've made your suggested change.

2023-09-27 13:59 UTC, rcooke-ast commented on pypeit/spectrographs/keck_kcwi.py
> +        binning : (str, `numpy.ndarray`_, tuple):
Done - thanks!

2023-09-27 13:59 UTC, rcooke-ast commented on pypeit/spectrographs/keck_kcwi.py
> +            formats, refer to `~pypeit.core.parse.parse_binning`.
Good catch - thanks!

2023-09-27 13:59 UTC, rcooke-ast commented on pypeit/spectrographs/keck_kcwi.py
> +        scattlightr = np.nanmedian(frame[:, -40//spatbin:], axis=1)[:, None]
I'm afraid not, for now. I think the eventual goal is to base this on the slit edges, but this is a little tricky to include in `rawimage.py`, so I'm leaving this as a TODO for now... I'll add a GH issue to remind ourselves that this is what we need to eventually be doing.

I'm also working on an alternative model for the KCWI+KCRM scattered light.

2023-09-27 13:59 UTC, rcooke-ast commented on pypeit/spectrographs/keck_kcwi.py
> +        return scatt_img
Comments added

2023-09-27 13:59 UTC, rcooke-ast commented on pypeit/spectrographs/spectrograph.py
> +            formats, refer to `~pypeit.core.parse.parse_binning`.
Fixed

2023-09-27 13:59 UTC, rcooke-ast commented on pypeit/core/parse.py
> +                -- this must be of the form of tuple, for example: np.array([2,1])
OK - I had it totally wrong, but I've now fixed this and it looks grand... It seems I'm learning new things with docstrings all the time!

2023-09-27 14:03 UTC, rcooke-ast commented
Sorry @kbwestfall, I forgot to address your other questions...

> * Can you add a description of this approach to the `keck_kcwi.rst` doc?

Yes, I will add this to Keck/KCWI docs.

> * Can we save the scattered light image somewhere?  In either or both of the `Flat` calilbration frame and the `spec2d` files?

I think this is not a good idea for the moment. I am working on a parameterised model that would need to store the model parameters, rather than an image (together with a routine that can generate the image from the model parameters). So, I'm tempted to wait until the next round of KCWI scattered light removal to incorporate this.

2023-09-27 15:08 UTC, kbwestfall commented on pypeit/core/parse.py
> +                -- this must be of the form of tuple, for example: np.array([2,1])
Yeah, I'm constantly learning the the ins and outs of docstrings / sphinx / rst, as well!

2023-09-27 15:19 UTC, kbwestfall commented
On saving the scattered light image, I'm fine with putting this off, but I wanted to advocate for saving the full image.  In similar situations I also used to be of the opinion that it's better to save the model parameters and provide a script if people want to reconstruct the model.  But I've come around to the opinion that this presents a barrier (albeit small) to people being able to assess the results.  Disk space is cheap and, IMO, enabling people to quickly open the file with astropy and view it with matplotlib is worth the cost of a larger output file.

2023-09-27 15:20 UTC, kbwestfall approved these changes
Approving!

2023-09-30 05:59 UTC, rcooke-ast commented
Tests pass
<img width="623" alt="image" src="https://github.com/pypeit/PypeIt/assets/12585758/a8ea8eea-ed92-4d3f-8ed9-e7576a0780de">

2023-10-01 17:44 UTC, jhennawi approved these changes
Approved. Thanks!

2023-10-01 18:50 UTC, merged