Use a modeled archival sky spectrum
pypeit/PypeIt pull request #1772
Opened 2024-02-15 22:44 UTC by debora-pe

This add the possibility to use a modeled sky spectrum (using `pypeit.wavemodel.nearIR_modelsky`) as archival sky spectrum in the spectral flexure correction.

It works well for data with wave > ~7500A, but I do not know if works better than the current method. Any thoughts?

This is currently directed to `bkg_redux_flexure`

2024-02-20 11:52 UTC, profxj requested changes
Mainly asking for clarity on a bit of the workflow.

Also, please add to the PR comments why this new
approach was implemented.  Thanks!

2024-02-20 11:52 UTC, profxj commented on pypeit/core/flexure.py
> +        spec_fwhm = spec_fwhm_pix * obj_disp
Please add a few inline docs on what is going on here

2024-02-20 11:52 UTC, profxj commented on pypeit/core/flexure.py
> +        obj_skyspec (`linetools.spectra.xspectrum1d.XSpectrum1d`_, optional):
Is it correct that this must be set if `sky_file == "model"`

if so, please note it.

2024-02-20 11:52 UTC, profxj commented on pypeit/core/flexure.py
> +            a model sky spectrum will be generated using see :func:`~pypeit.wavemodel.nearIR_modelsky`.
note that it will be generated from an analysis of `obj_skyspec`

2024-02-20 11:52 UTC, profxj commented on pypeit/core/flexure.py
> +    fdict = spec_flex_shift(slit_specs[islit], sky_file, mxshft=mxshft, excess_shft=excess_shft,
as `sky_file=="model"` requires the `obj_sky_spec` this method can't use that option, right?   just checking

2024-02-20 11:52 UTC, profxj commented on pypeit/core/flexure.py
> +        fdict = spec_flex_shift(obj_sky, sky_file, mxshft=mxshft, excess_shft=excess_shft,
same point as above.  seems to me `sky_file=="model"` isn't allowed here

2024-02-20 11:52 UTC, profxj commented on pypeit/core/skysub.py
> +    return skyimage[thismask], nobkg_skyimage[thismask] if nobkg_skyimage is not None else None, \
can you document why `nobkg_skyimage` may be `None`?

Maybe add it to the `Returns` portion of the doc string

2024-02-20 11:52 UTC, profxj commented on pypeit/par/pypeitpar.py
> +                             'If ``model`` is used, a model sky spectrum will be generated '
point out here too it is generated from the the `objsky` spectrum, i.e. its resolution, etc.

2024-02-20 20:07 UTC, badpandabear approved these changes
Looks good to me.

2024-02-20 20:07 UTC, badpandabear commented on pypeit/extraction.py
> +            self.skymodel[thismask], _tihs_nobkg_skymodel, self.ivarmodel[thismask], self.extractmask[thismask] \
Should this be `_this_nobkg_skymodel` instead of `_tihs_nobkg_skymodel`

2024-02-24 03:54 UTC, debora-pe commented
> Mainly asking for clarity on a bit of the workflow.
> 
> Also, please add to the PR comments why this new approach was implemented. Thanks!

Thanks @profxj .

This new approach was implemented to improve the flexure correction. It is not clear it is better than the current approach, but it definitely helps in the case when the object's spectral resolution is higher that the resolution of the archival spectrum.

2024-02-24 12:39 UTC, profxj approved these changes
very good;

merge when you wish.

thanks!

2024-02-28 04:13 UTC, merged