fixed PHOENIX A0V atmosphere read error & identify save error
pypeit/PypeIt pull request #1828
Opened 2024-07-05 17:14 UTC by Adolfo1519

2024-07-08 13:46 UTC, VascoSch92 commented on pypeit/core/gui/identify.py
> +                                print('               ')
```suggestion
                                print('  '*10)
```
it is a little bit better to read :-)

2024-07-08 18:48 UTC, Adolfo1519 commented on pypeit/core/gui/identify.py
> +                                print('               ')
Thank you!

2024-07-08 20:30 UTC, rcooke-ast approved these changes
Looks good to me - thanks for implementing the fix!

2024-07-08 20:30 UTC, rcooke-ast commented on pypeit/core/gui/identify.py
> +                            slit_list_str = ''; slit_list = np.arange(np.shape(specdata_multi)[0])
For readability, please write this on two seaprate lines
```
slit_list_str = ''
slit_list = np.arange(np.shape(specdata_multi)[0])
```

2024-07-09 20:08 UTC, kbwestfall requested changes
Looks good to me.  Please add a comment to the `doc/releases/1.16.1dev.rst` file.

2024-07-09 20:08 UTC, kbwestfall commented on pypeit/core/flux_calib.py
> +            vega_file = dataPaths.standards.get_file_path('PHOENIX_10000K_4p0.fits')
Nice!

2024-07-09 20:08 UTC, kbwestfall commented on pypeit/core/gui/identify.py
> +                            slit_list_str = ''; slit_list = np.arange(np.shape(specdata_multi)[0])
Yes, please!

2024-07-09 20:57 UTC, Adolfo1519 commented on pypeit/core/gui/identify.py
> +                            slit_list_str = ''; slit_list = np.arange(np.shape(specdata_multi)[0])
done!

2024-07-09 20:57 UTC, Adolfo1519 commented on pypeit/core/flux_calib.py
> +            vega_file = dataPaths.standards.get_file_path('PHOENIX_10000K_4p0.fits')
Thanks!

2024-07-15 15:17 UTC, kbwestfall approved these changes
Thanks for the update to the release doc!

2024-08-12 21:56 UTC, merged